"""Add checkout_request_id and order link

Revision ID: 2af6bfe27643
Revises: 4dfdfd185991
Create Date: 2026-01-13 14:32:00.774864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af6bfe27643'
down_revision = '4dfdfd185991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_transaction_monitor'))
        batch_op.create_index(batch_op.f('ix_transactions_checkout_request_id'), ['checkout_request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_checkout_request_id'))
        batch_op.create_index(batch_op.f('idx_transaction_monitor'), ['status', 'created_at'], unique=False)
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
