"""Added delivery_location to Order

Revision ID: 4dfdfd185991
Revises: c5055b4ff8cd
Create Date: 2026-01-12 17:21:52.890198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfdfd185991'
down_revision = 'c5055b4ff8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('mpesa_receipt_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('mpesa_receipt_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_location')

    # ### end Alembic commands ###
