"""Add GPS to Orders

Revision ID: 7e3406595a7d
Revises: 2af6bfe27643
Create Date: 2026-01-14 10:02:05.262974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3406595a7d'
down_revision = '2af6bfe27643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('customer_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('customer_longitude')
        batch_op.drop_column('customer_latitude')

    # ### end Alembic commands ###
