"""Initial migration for Postgres

Revision ID: c5055b4ff8cd
Revises: 
Create Date: 2026-01-12 13:40:37.045841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5055b4ff8cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vendor_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_locations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
